### PR TITLE
AND-3996 | Enable/Disable Video calling from setting screen

### PR DESCRIPTION
**Pull request by pratik-pdc**
- Fix added to resolve crash on register/de-register for video calling

### CODE REVIEW

**Review by hchauhansf — APPROVED** [review]
Looks good to merge 👍

**Comment by pratik-pdc** [comment]
@hchauhansf Please review.

**Review by hchauhansf — APPROVED** [review]
Looks good to merge 👍

**Review by hchauhansf — APPROVED** [review]
Good to merge 👍

**Review by pratik-pdc — COMMENTED** [review]
Review done!

**Pull request merged**
